<?php

namespace Tests\Unit;

use App\Events\FinalOverviewEvent;
use App\Events\PreviouslyAnswersEvent;
use App\Events\QuestionsProgressEvent;
use App\Models\User;
use App\Services\EventService;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;


class EventsTest extends TestCase
{
    use DatabaseMigrations, DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->event = new EventService();
        $this->user = factory(User::class)->create();

    }

    public function testQuestionsProgressEvents()
    {
        Event::fake();
        $this->event->startQuestionsProgressEvent($this->user);

        Event::assertDispatched(QuestionsProgressEvent::class);
    }

    public function testPreviouslyAnswersEvent()
    {
        Event::fake();
        $this->event->startPreviouslyAnswersEvent($this->user);

        Event::assertDispatched(PreviouslyAnswersEvent::class);
    }

    public function testStartFinalOverviewEvent()
    {
        Event::fake();
        $this->event->startFinalOverviewEvent($this->user);

        Event::assertDispatched(FinalOverviewEvent::class);
    }
}
